### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#16]
Add i18nsupport on the model of https://github.com/lingua-libre/RecordWizard/tree/master/i18n .
- [x] Create `/i18n/`
- [x] Add qqq.json
- [x] Add en.json
- [x] Add fr.json 
- [x] Add language UI in settings
- [x] Load translation file
- [x] Use translation file
- [x] Works, need to clean the mess.
- [x] Restore wpintegration and overlay

**Comment by hugolpz** [comment]
@Amire80, I need your expertise on translation.
I want to add a `/i18n/` folder, already started, to this websapp. I added `en.json`, `fr.json`, and `qqq.json`.

1. I assume qqq.json is some sort of template, is that right ?
2. how do I activate translate wiki on this repository ?
3. can I rename my files into js files ? Should I ?
4. If you have the ability and free time to help this js effort (externalizing message strings), feel free to jump in.

**Comment by amire80** [comment]
Hi! Thanks for the question :)

1. qqq.json must have the same keys as en.json, but the content must be different. Every value of the key must not repeat the English message, but explain it for the translators. This is necessary for correct translation. For example, the message si-popup-history-noHistory says "It's empty". _What_ is empty? "It" may be translated differently into many languages, depending on the thing to which it refers, for example because of grammatical gender. And the same must be done with all the keys.
2. Ask at https://translatewiki.net/wiki/Support . Also, see https://translatewiki.net/wiki/Translating:New_project for more technical details.
3. You shouldn't change to JS. JS is for code, JSON is for data. Strings and translations are data. Also, JSON is easily compatible with translatewiki.

About "Load translation file": I have neither tried running the app nor read its code deeply. Do you already have a way to load the files? If not, consider https://github.com/wikimedia/jquery.i18n or https://github.com/wikimedia/banana-i18n .

About "Add language UI in settings": Consider https://github.com/wikimedia/jquery.uls .

**Comment by hugolpz** [comment]
Well underway.
