### ISSUE TITLE
Bubble on selection positioning

### ISSUE THREAD

**Issue by edouard-lopez** [lingua-libre/SignIt#33]
Thanks for adding this feature, it make it so easier to use!

### Actual
I use other extension like signIt to translate selected text, and they are overlapping, below you can see La Bulle Elix is completely overlaping SignIt (we can see a part of the wing on the top left):

![image](https://user-images.githubusercontent.com/1212392/184357858-66275cbf-b782-45a6-9651-f255ae7362b7.png)

### Expectation
The [Simple Translate](https://addons.mozilla.org/en-US/firefox/addon/simple-translate/) lets user choose where they want it display
![image](https://user-images.githubusercontent.com/1212392/184358645-0adf6abb-399c-4df6-a252-aedd1cdd97eb.png)

### Request

How feasible is it to be able to select the position?

**Comment by pushkar707** [comment]
Hi @hugolpz ,

I would like to work on this issue.

**Comment by hugolpz** [comment]
@pushkar707 hello,
Please wait. We have to handle some paperwork before we are back into the GSoC. Also, one requirement of the GSoC is to do a microtask starting on March 18th. So better to wait then.

**Comment by pushkar707** [comment]
@hugolpz okay, I understand that you are busy at the moment, so I won't comment on any issues for now, and keep making myself familiar to the codebase, then after 18th March maybe I will initiate the PRs

**Comment by pushkar707** [comment]
@hugolpz okay, I understand that you are busy at the moment, so I won't comment on any issues for now, and keep making myself familiar to the codebase, then after 18th March maybe I will initiate the PRs

**Comment by Kamalkishor0** [comment]
Hey @hugolpz ,
 I would like to work on this issue.

**Comment by hugolpz** [comment]
Hello @Kamalkishor0 , the codebase is unstable since Kabir and myself work on it this summer. 
May I contact you again this automn ? we will plan for small tasks to distribute among volunteer developers.

**Comment by hugolpz** [comment]
Hello @saltykheera,
Thank you for this.
I'm on the road again heading to Poland's Wikimania 2024. I wont have much computer time. I can review your code tomorrow (08/01) evening or on 08/03. 👍🏼

**Comment by hugolpz** [comment]
Hello Salthy,
I have difficulties to see where were your changes due to both prettyfier and behaviors changes being in the same commit. Ignoring white space merely help since there are added linebreak all around.

The code is organized differently for your additions, on `popup.js` i can see two ways:
- all your code is together, which make mirroring and comparing with previous code blocks harder [#L294-L325](https://github.com/saltykheera/SignIt/blob/d591fd1e3a8abe8c599e89c1375413ba3aac1c81/popup/popup.js#L294-L325)
- you do not reuse a `change` function [#L477-L500](https://github.com/saltykheera/SignIt/blob/d591fd1e3a8abe8c599e89c1375413ba3aac1c81/popup/popup.js#L477-L500) , you move to more direct code.
- but i see a different pattern, instead of `await sendMessageUp("changeUiLanguage", newLanguage);` you use `sendMessageUp("storeParam", ["position", selectedPosition]);`, which is new and I don't know if supported.

Overall you are doing too much in one commit : 1. prettifying ; 2. adding a behavior ; 3. trying alternative coding way. (This with a junior dev teammate traveling abroad for conference, starts to make a lot !)

Maybe also, I don't see creation of the strings in ./i18n/en.json or any language.
Since you use them, you will have to add them :
```json
	"si-popup-settings-position":"Hint icon position:",
	"si-popup-settings-position-help":"Change default position for the hint icon.",
```
Into [i18n/en.json#43]https://github.com/saltykheera/SignIt/blob/master/i18n/en.json#L43 .
The labels will only show up if your SignIt UI settings is set to English. We need to edit the other json so the label shows in other languages as well.

**Comment by saltykheera** [comment]
@hugolpz currently i am ignoring i18 
after i fix this issue i will add it later not the naming in used to to remind me of that .
because i work in english and of i changed the language it is difficult for me to navigate

2> you are right abut the prettyfy thing 
and i will make sure i completed disable it before i make the next commit 

3> i am getting your point of using missing label i will try again freshly am make the necessary commit and if required PR on thru morning positively 


thanks 😊  for for time and help 
your commitment for work also pushes me 

i try i wont be a ache next time with my code

**Comment by hugolpz** [comment]
No prob, I see the good will. 🥇  It's just a bit challenging to follow but it's good. 👍🏼

**Comment by hugolpz** [comment]
Some labels to clean up a bit further.
