### ISSUE TITLE
Onboard @kabir-afk

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#49]
Hello @kabir-afk , following your email I'm happy to grant you contributor rights.
Few rapid things to know 👍🏼 
- Legacy: This web extension project is 5 years old, quite modest and now a bit messy, but still okish, and I'm around to answer questions.
- [Manifest v2](https://developer.chrome.com/docs/extensions/mv2) : Please note this current code is v2, which will become deprecated on Extensions stores
- #21 : Being a junior developer handling legacy code, I have the way but I'm struggling to migrate to v3. 
- Few codes coming : please wait a week or two to edit this repository, I got some local changes waiting to be pushed to github. A tiny new feature.
- It may be more time-efficient to study this version and recreate it from scratch using Manifest v3 boilerplate and ChatGPT's help. See #21 section `V3 from scratch ?` for leads.
- I actually look for someone to lead the development side so I may focus on coordinating partners to create more signed videos. While the project could receive all sign languages and the UI is translated in 30 langues, we only have video data for French Sign Language. Which is far too little.

You have the gist of it. The rest is coding and project management.

**Comment by kabir-afk** [comment]
Hey man , thanks for consideration. I just had a few more doubts and
request to make which I thought of making personally:
Requests :-
 - Expectations : Pls don't expect high of me . . .I've never  worked on
open-sourced projects before and this is my first time , not to mention
that I myself expect this to be a growth step for me. I am mentioning this
since you said :
"I actually look for someone to lead the development side so I may focus on
coordinating partners to create more signed videos"
so that kinda put me in spot 😅
 - Communication : It would really ease my workflow if I could directly DM
you and clarify my doubts on other platforms like , discord ,etc rather
than having to write email every single time.

discord username: kabir3283

Doubts:-
 - GSoC : I was hoping that you'd guide me for gsoc as well if this project
is enlisted in this year's project of wikimedia . . .I'm not solely here
for gsoc , I just want to learn enough that I am able to contribute in gsoc
projects as well one day , but it'll be great if I were to work under this
in gsoc as well. Also I was wondering whether this project was a part of
previous year's projects ?
 - I'll be working on migrating manifest v2 files to v3 right ? Which is
for the chrome version of the extension?

That is all , thanks again for consideration

**Comment by kabir-afk** [comment]
Hey man , I apologize in advance , I know you asked me not to edit the code but I've already updated manifest file from V2 to V3 which was under Issue: 21 , I dont think it would interfere with your workflow/the changes you were about to make locally  so I gave it a go , opening a PR rn , you can review the changes and merge them whenever you feel like

**Comment by hugolpz** [comment]
No prob. If you go fast you go fast. The feature I'm working on is tiny, I can redo it.

**Comment by kabir-afk** [comment]
okkk then, but do you mind reviewing the PR  , as well as can you clear my doubt regarding GSoC as mentioned above ? It'll really help me out

**Comment by hugolpz** [comment]
@kabir-afk Hello,
My apologize this week is heavily loaded on the work side so i'm brain exhausted. Let me try to answer as best as I can.

**Expectations:** all fine by me, we are volunteers, not on duty. I wanted to convey that the door is open if you want to. Our general idea is to have fun, help positive changes and get new skills as volunteers devs.¹ As for GSoC, see below. 

**Communication:** I just sent you an email with chat chanels to continue more efficient synchroneous discussion

**GSoC doubts:** Lingualibre has not joined any previous GSoC edition so far. We are interested by GSoC. But in previous years we hadn't the human time resources or knowledge to actually get involved in it. We have to ask Wikimedia staff or volunteers who already participated the GSoC and mentored developers to learn how to do so. 

**Manifest v2 to v3:** I'm checking this PR.

cc @Poslovitch .
1: Disclaimer :  I'm currently Wikimedian in Residence in Toulouse for training University staff to Wikimedia projects. My github developements on Lingualibre have been and are volunteer.

**Comment by kabir-afk** [comment]
hey thanks man for all the effort , I'll test run the extension as well when I'm done with all the steps that come under migration.
The reason I asked about gsoc ,was because ,under new developers' projects in wikimedia , this project was mentioned as well , along with VideoCutTool and Scribe. [See here](https://www.mediawiki.org/wiki/New_Developersl) . So I thought maybe this extension was part of gsoc as well . . . you'll be able to look into it better ig.

**Comment by hugolpz** [comment]
Bonjour @kabir-afk ,
Thank you for your arrival path info. You are the 2n person contacting me for GSoC this January which puzzled me. The page you shared list Wikimedia coding projects welcoming or in need of new volunteer developpers. Part of these WM projects are also participating GSoC, but not all of them. I added Lingualibre to that list in July. Lingualibre havent participated to GSoC so far.

**Comment by kabir-afk** [comment]
Thanks for the clarification . . . I'll keep contributing whenever I get the time  . . . genuinely
